# Generated by Django 3.0a1 on 2019-09-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('success', models.BooleanField()),
                ('base', models.CharField(default='BTC', max_length=10)),
                ('target', models.CharField(default='USD', max_length=10)),
                ('price', models.FloatField()),
                ('error', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddConstraint(
            model_name='currencymodel',
            constraint=models.UniqueConstraint(fields=('base', 'target'), name='unique_base_and_target'),
        ),
    ]
