# Generated by Django 3.0a1 on 2019-09-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190917_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='base',
            field=models.CharField(choices=[('USD', 'usd'), ('BTC', 'btc'), ('RUR', 'rur')], max_length=10),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='target',
            field=models.CharField(choices=[('USD', 'usd'), ('BTC', 'btc'), ('RUR', 'rur')], max_length=10),
        ),
    ]
